apiVersion: v2
name: gluon
description: A Library Helm chart for BigBang

type: library

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.9.8
annotations:
  helm.sh/images: |
    - name: kubectl
      image:  registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.34
    - name: cypress
      image: registry1.dso.mil/ironbank/big-bang/cypress:15.10.0
